import { Bot, ChevronDown, ChevronUp } from 'lucide-react';
import { useState } from 'react';

interface DocumentSummaryProps {
  summary: string | null;
  isLoading: boolean;
  error?: string | null;
  onGenerate: () => void;
}

export default function DocumentSummary({
  summary,
  isLoading,
  error,
  onGenerate,
}: DocumentSummaryProps) {
  const [isOpen, setIsOpen] = useState(true);

  return (
    <section className="bg-sky-50 border border-sky-100 rounded-2xl overflow-hidden">
      <button
        type="button"
        onClick={() => setIsOpen((value) => !value)}
        className="w-full flex items-center justify-between gap-3 px-5 py-4 text-left"
      >
        <div className="flex items-center gap-2">
          <Bot className="w-5 h-5 text-sky-700" />
          <h2 className="text-lg font-semibold text-primary">AI Summary</h2>
        </div>
        {isOpen ? (
          <ChevronUp className="w-5 h-5 text-subtext" />
        ) : (
          <ChevronDown className="w-5 h-5 text-subtext" />
        )}
      </button>

      {isOpen && (
        <div className="px-5 pb-5">
          {summary ? (
            <p className="text-[15px] leading-7 text-[#333333] whitespace-pre-wrap">{summary}</p>
          ) : isLoading ? (
            <div className="space-y-2 animate-pulse">
              <div className="h-4 bg-sky-100 rounded w-full" />
              <div className="h-4 bg-sky-100 rounded w-11/12" />
              <div className="h-4 bg-sky-100 rounded w-4/5" />
            </div>
          ) : error ? (
            <div className="space-y-3">
              <p className="text-sm text-red-700">{error}</p>
              <button
                type="button"
                onClick={onGenerate}
                className="text-sm font-medium text-accent hover:underline"
              >
                Retry summary
              </button>
            </div>
          ) : (
            <button
              type="button"
              onClick={onGenerate}
              className="text-sm font-medium text-accent hover:underline"
            >
              Generate AI summary
            </button>
          )}

          <p className="mt-4 text-xs text-subtext">
            Generated by AI — verify with full text
          </p>
        </div>
      )}
    </section>
  );
}
